CustomerManagementSystem - Copy/CustomerManagementSystem/Controllers/CustomerListController.cs
using CustomerManagementSystem.Domain;
using CustomerManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CustomerManagementSystem.Controllers
{
    public class CustomerListController : Controller
    {

        [Authorize(Roles="Admin")]
        public ActionResult CustomerList()
        {
            using (CustomerManagementContext dbContext = new CustomerManagementContext())
            {
                CustomerListModel customerListModel = new CustomerListModel();
                customerListModel.customers = dbContext.Customers.Where(Customer=>Customer.deleted_at==null).ToList();
                return View(customerListModel);
            }
           
        }
        [Authorize(Roles = "Admin")]
        public void DeleteCustomer(long customer_Id)
        {
            using (CustomerManagementContext dbContext = new CustomerManagementContext())
            {
                var Customer = dbContext.Customers.FirstOrDefault(Customers => Customers.customer_id == customer_Id);
                if (Customer != null)
                {
                     Customer.deleted_at = DateTime.Now;
                    dbContext.SaveChanges();
                }
                var user = dbContext.users.FirstOrDefault(Users => Users.customer_id == customer_Id);
                if(user != null)
                {
                    user.status = false;
                    user.deleted_at=DateTime.Now;
                    dbContext.SaveChanges();
                }
            }

        }
    }
}

CustomerManagementSystem - Copy/CustomerManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @*@Styles.Render("~/Content/css")*@
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/DataTables/css/CustomerList.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <script src="~/Scripts/Custom/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand text-light" href="#">Customer Management System</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav d-flex align-items-center justify-content-between" style="width:100%">
                    <div class="d-flex align-items-center justify-content-between">
                        <a class="nav-link active" aria-current="page" @Html.ActionLink("Home", "CustomerList", "CustomerList")>Home</a>
                    </div>
                    <div class="d-flex align-items-center justify-content-between">
                        @if (User.Identity.IsAuthenticated)
                        {
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    @User.Identity.Name
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-start " aria-labelledby="navbarDropdownMenuLink">
                                    <li class="dropdown-item">@Html.ActionLink("Change Password", "ChangePassword", "User", new { @class = "dropdown-item" }, new { @style = "text-decoration:none; color:black" })</li>
                                    <li class="dropdown-item"> @Html.ActionLink("Edit Profile", "UserEditProfile", "User", new { @class = "dropdown-item" }, new { @style = "text-decoration:none; color:black" })</li>
                                    <li>  <a class="dropdown-item" onclick="LogOut()">Log Out </a></li>
                                </ul>
                            </li>
                        </ul>

                        }
                        else
                        {
                            <a class="nav-link" @Html.ActionLink("Login", "Login", "Account")></a>
                        }
                    </div>

                </div>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>

<script src="~/Scripts/Custom/CustomerList.js"></script>
<script src="~/Scripts/Custom/LogOut.js"></script>